trigger: 
- main
#- devops/*

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd express-backend
    npm install
  displayName: 'Install backend dependencies'

- script: |
    cd react-frontend
    npm install
    npm run build
  displayName: 'npm install and build'
